# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        exclude: migrations
        args: [--profile, black, --line-length=80]
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=79]
